### ISSUE TITLE
RouteGateway typo

### ISSUE THREAD

**Issue by wlc99** [piomin/sample-camel-spring-boot#5]
### There seems to be a cut & paste error in RouteGateway.java

    JacksonDataFormat formatAccList = new JacksonDataFormat(Account.class);
    formatAccList.useList();
    JacksonDataFormat formatCusList = new JacksonDataFormat(Customer.class);
    formatAccList.useList();  --> Should be formatCusList.useList();

Thanks.

**Comment by piomin** [comment]
fixed
